# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Dragoncore/PipeLine/PipeLine.srcs/sources_1/ip/Data_Ram/Data_Ram.xci
# IP: The module: 'Data_Ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Dragoncore/PipeLine/PipeLine.srcs/sources_1/ip/Data_Ram/Data_Ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Dragoncore/PipeLine/PipeLine.srcs/sources_1/ip/Data_Ram/Data_Ram.xci
# IP: The module: 'Data_Ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Dragoncore/PipeLine/PipeLine.srcs/sources_1/ip/Data_Ram/Data_Ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
